2025-09-23 18:22:25,468 - distributed.worker - WARNING - Compute Failed
Key:       compute_and_save_daily_mean-db9ee5cb-37f9-4d30-b080-2288480bd4ee
Function:  execute_task
args:      ((<function compute_and_save_daily_mean at 0x7f83d369fc70>, '/work_big/users/clima/portal/CRCM5-LE/psl/kbg/2085/psl_EUR-11_CCCma-CanESM2_rcp85_r1-r7i1p1_OURANOS-CRCM5_kbg_3h_208510.nc', '/work_big/users/clima/portal/CRCM5-LE/psl/kbg/2085/psl_EUR-11_CCCma-CanESM2_rcp85_r1-r7i1p1_OURANOS-CRCM5_kbg_daily_208510.nc', 'psl', (<class 'dict'>, [['psl', (<class 'dict'>, [['zlib', 'True'], ['complevel', 5], ['dtype', 'float32']])]])))
kwargs:    {}
Exception: "FileNotFoundError(2, 'No such file or directory')"

2025-09-23 18:22:25,470 - distributed.worker - WARNING - Compute Failed
Key:       compute_and_save_daily_mean-423f337e-8f0b-4584-8340-71d58675e4d0
Function:  execute_task
args:      ((<function compute_and_save_daily_mean at 0x7f83d369fc70>, '/work_big/users/clima/portal/CRCM5-LE/psl/kbg/2085/psl_EUR-11_CCCma-CanESM2_rcp85_r1-r7i1p1_OURANOS-CRCM5_kbg_3h_208508.nc', '/work_big/users/clima/portal/CRCM5-LE/psl/kbg/2085/psl_EUR-11_CCCma-CanESM2_rcp85_r1-r7i1p1_OURANOS-CRCM5_kbg_daily_208508.nc', 'psl', (<class 'dict'>, [['psl', (<class 'dict'>, [['zlib', 'True'], ['complevel', 5], ['dtype', 'float32']])]])))
kwargs:    {}
Exception: "FileNotFoundError(2, 'No such file or directory')"

2025-09-23 18:22:25,472 - distributed.worker - WARNING - Compute Failed
Key:       compute_and_save_daily_mean-87a819fe-fd8a-4377-a55c-f77a560cec35
Function:  execute_task
args:      ((<function compute_and_save_daily_mean at 0x7f83d369fc70>, '/work_big/users/clima/portal/CRCM5-LE/psl/kbg/2085/psl_EUR-11_CCCma-CanESM2_rcp85_r1-r7i1p1_OURANOS-CRCM5_kbg_3h_208507.nc', '/work_big/users/clima/portal/CRCM5-LE/psl/kbg/2085/psl_EUR-11_CCCma-CanESM2_rcp85_r1-r7i1p1_OURANOS-CRCM5_kbg_daily_208507.nc', 'psl', (<class 'dict'>, [['psl', (<class 'dict'>, [['zlib', 'True'], ['complevel', 5], ['dtype', 'float32']])]])))
kwargs:    {}
Exception: "FileNotFoundError(2, 'No such file or directory')"

2025-09-23 18:22:25,472 - distributed.worker - WARNING - Compute Failed
Key:       compute_and_save_daily_mean-2aac3c02-9d78-4c23-a861-a9fce754d5dd
Function:  execute_task
args:      ((<function compute_and_save_daily_mean at 0x7f83d369fc70>, '/work_big/users/clima/portal/CRCM5-LE/psl/kbg/2085/psl_EUR-11_CCCma-CanESM2_rcp85_r1-r7i1p1_OURANOS-CRCM5_kbg_3h_208501.nc', '/work_big/users/clima/portal/CRCM5-LE/psl/kbg/2085/psl_EUR-11_CCCma-CanESM2_rcp85_r1-r7i1p1_OURANOS-CRCM5_kbg_daily_208501.nc', 'psl', (<class 'dict'>, [['psl', (<class 'dict'>, [['zlib', 'True'], ['complevel', 5], ['dtype', 'float32']])]])))
kwargs:    {}
Exception: "FileNotFoundError(2, 'No such file or directory')"

Traceback (most recent call last):
  File "/home/portal/script/python/compute_daily-mean_dask.py", line 56, in <module>
    dask.compute(*dd)
  File "/home/portal/anaconda3/envs/myenv/lib/python3.10/site-packages/dask/base.py", line 661, in compute
    results = schedule(dsk, keys, **kwargs)
  File "/home/portal/script/python/functions_preprocessing.py", line 46, in compute_and_save_daily_mean
    ds = xr.open_dataset(file_in)
  File "/home/portal/anaconda3/envs/myenv/lib/python3.10/site-packages/xarray/backends/api.py", line 539, in open_dataset
    backend_ds = backend.open_dataset(
  File "/home/portal/anaconda3/envs/myenv/lib/python3.10/site-packages/xarray/backends/netCDF4_.py", line 572, in open_dataset
    store = NetCDF4DataStore.open(
  File "/home/portal/anaconda3/envs/myenv/lib/python3.10/site-packages/xarray/backends/netCDF4_.py", line 376, in open
    return cls(manager, group=group, mode=mode, lock=lock, autoclose=autoclose)
  File "/home/portal/anaconda3/envs/myenv/lib/python3.10/site-packages/xarray/backends/netCDF4_.py", line 323, in __init__
    self.format = self.ds.data_model
  File "/home/portal/anaconda3/envs/myenv/lib/python3.10/site-packages/xarray/backends/netCDF4_.py", line 385, in ds
    return self._acquire()
  File "/home/portal/anaconda3/envs/myenv/lib/python3.10/site-packages/xarray/backends/netCDF4_.py", line 379, in _acquire
    with self._manager.acquire_context(needs_lock) as root:
  File "/home/portal/anaconda3/envs/myenv/lib/python3.10/contextlib.py", line 135, in __enter__
    return next(self.gen)
  File "/home/portal/anaconda3/envs/myenv/lib/python3.10/site-packages/xarray/backends/file_manager.py", line 197, in acquire_context
    file, cached = self._acquire_with_cache_info(needs_lock)
  File "/home/portal/anaconda3/envs/myenv/lib/python3.10/site-packages/xarray/backends/file_manager.py", line 215, in _acquire_with_cache_info
    file = self._opener(*self._args, **kwargs)
  File "src/netCDF4/_netCDF4.pyx", line 2463, in netCDF4._netCDF4.Dataset.__init__
  File "src/netCDF4/_netCDF4.pyx", line 2026, in netCDF4._netCDF4._ensure_nc_success
FileNotFoundError: [Errno 2] No such file or directory: b'/work_big/users/clima/portal/CRCM5-LE/psl/kbg/2085/psl_EUR-11_CCCma-CanESM2_rcp85_r1-r7i1p1_OURANOS-CRCM5_kbg_3h_208510.nc'
2025-09-23 18:22:25,491 - distributed.worker.state_machine - WARNING - Async instruction for <Task cancelled name="execute('compute_and_save_daily_mean-fe62f948-653e-4bf8-84b7-50ca92ef9f42')" coro=<Worker.execute() done, defined at /home/portal/anaconda3/envs/myenv/lib/python3.10/site-packages/distributed/worker_state_machine.py:3615>> ended with CancelledError
2025-09-23 18:22:25,491 - distributed.worker.state_machine - WARNING - Async instruction for <Task cancelled name="execute('compute_and_save_daily_mean-385cc343-5089-42c6-83f5-25fc4a7cb059')" coro=<Worker.execute() done, defined at /home/portal/anaconda3/envs/myenv/lib/python3.10/site-packages/distributed/worker_state_machine.py:3615>> ended with CancelledError
2025-09-23 18:22:25,491 - distributed.worker - WARNING - Compute Failed
Key:       compute_and_save_daily_mean-17eb9a7c-e97d-40b4-bcf5-a31799c5c4e7
Function:  execute_task
args:      ((<function compute_and_save_daily_mean at 0x7f365334bc70>, '/work_big/users/clima/portal/CRCM5-LE/psl/kbg/2085/psl_EUR-11_CCCma-CanESM2_rcp85_r1-r7i1p1_OURANOS-CRCM5_kbg_3h_208506.nc', '/work_big/users/clima/portal/CRCM5-LE/psl/kbg/2085/psl_EUR-11_CCCma-CanESM2_rcp85_r1-r7i1p1_OURANOS-CRCM5_kbg_daily_208506.nc', 'psl', (<class 'dict'>, [['psl', (<class 'dict'>, [['zlib', 'True'], ['complevel', 5], ['dtype', 'float32']])]])))
kwargs:    {}
Exception: "FileNotFoundError(2, 'No such file or directory')"

2025-09-23 18:22:25,492 - distributed.worker - WARNING - Compute Failed
Key:       compute_and_save_daily_mean-3fc41aaf-d7e4-4ef6-b96d-7eabea8e5fa3
Function:  execute_task
args:      ((<function compute_and_save_daily_mean at 0x7f365334bc70>, '/work_big/users/clima/portal/CRCM5-LE/psl/kbg/2085/psl_EUR-11_CCCma-CanESM2_rcp85_r1-r7i1p1_OURANOS-CRCM5_kbg_3h_208502.nc', '/work_big/users/clima/portal/CRCM5-LE/psl/kbg/2085/psl_EUR-11_CCCma-CanESM2_rcp85_r1-r7i1p1_OURANOS-CRCM5_kbg_daily_208502.nc', 'psl', (<class 'dict'>, [['psl', (<class 'dict'>, [['zlib', 'True'], ['complevel', 5], ['dtype', 'float32']])]])))
kwargs:    {}
Exception: "FileNotFoundError(2, 'No such file or directory')"

2025-09-23 18:22:25,492 - distributed.worker - WARNING - Compute Failed
Key:       compute_and_save_daily_mean-c076ca26-136b-452d-ab20-70e3ce934d9d
Function:  execute_task
args:      ((<function compute_and_save_daily_mean at 0x7f365334bc70>, '/work_big/users/clima/portal/CRCM5-LE/psl/kbg/2085/psl_EUR-11_CCCma-CanESM2_rcp85_r1-r7i1p1_OURANOS-CRCM5_kbg_3h_208505.nc', '/work_big/users/clima/portal/CRCM5-LE/psl/kbg/2085/psl_EUR-11_CCCma-CanESM2_rcp85_r1-r7i1p1_OURANOS-CRCM5_kbg_daily_208505.nc', 'psl', (<class 'dict'>, [['psl', (<class 'dict'>, [['zlib', 'True'], ['complevel', 5], ['dtype', 'float32']])]])))
kwargs:    {}
Exception: "FileNotFoundError(2, 'No such file or directory')"

2025-09-23 18:22:25,492 - distributed.worker.state_machine - WARNING - Async instruction for <Task cancelled name="execute('compute_and_save_daily_mean-a1fc202f-b0b3-4293-87de-904c1938541d')" coro=<Worker.execute() done, defined at /home/portal/anaconda3/envs/myenv/lib/python3.10/site-packages/distributed/worker_state_machine.py:3615>> ended with CancelledError
2025-09-23 18:22:25,493 - distributed.worker.state_machine - WARNING - Async instruction for <Task cancelled name="execute('compute_and_save_daily_mean-5043ef7e-cbfd-4e06-976c-0739af1dc57f')" coro=<Worker.execute() done, defined at /home/portal/anaconda3/envs/myenv/lib/python3.10/site-packages/distributed/worker_state_machine.py:3615>> ended with CancelledError
2025-09-23 18:22:25,494 - distributed.worker.state_machine - WARNING - Async instruction for <Task cancelled name="execute('compute_and_save_daily_mean-62f3192e-ee57-4b9a-9db9-1c5aba68efe2')" coro=<Worker.execute() done, defined at /home/portal/anaconda3/envs/myenv/lib/python3.10/site-packages/distributed/worker_state_machine.py:3615>> ended with CancelledError

real	0m2.696s
user	0m5.228s
sys	0m11.440s
