2025-09-23 18:23:28,522 - distributed.worker - WARNING - Compute Failed
Key:       compute_and_save_daily_mean-3c6a3b77-752b-4213-9105-9b257d69d4a3
Function:  execute_task
args:      ((<function compute_and_save_daily_mean at 0x7f21d8db3c70>, '/work_big/users/clima/portal/CRCM5-LE/psl/kbg/2099/psl_EUR-11_CCCma-CanESM2_rcp85_r1-r7i1p1_OURANOS-CRCM5_kbg_3h_209906.nc', '/work_big/users/clima/portal/CRCM5-LE/psl/kbg/2099/psl_EUR-11_CCCma-CanESM2_rcp85_r1-r7i1p1_OURANOS-CRCM5_kbg_daily_209906.nc', 'psl', (<class 'dict'>, [['psl', (<class 'dict'>, [['zlib', 'True'], ['complevel', 5], ['dtype', 'float32']])]])))
kwargs:    {}
Exception: "FileNotFoundError(2, 'No such file or directory')"

2025-09-23 18:23:28,524 - distributed.worker - WARNING - Compute Failed
Key:       compute_and_save_daily_mean-a374c70c-687d-4d0e-a929-d9899b2397ea
Function:  execute_task
args:      ((<function compute_and_save_daily_mean at 0x7f21d8db3c70>, '/work_big/users/clima/portal/CRCM5-LE/psl/kbg/2099/psl_EUR-11_CCCma-CanESM2_rcp85_r1-r7i1p1_OURANOS-CRCM5_kbg_3h_209907.nc', '/work_big/users/clima/portal/CRCM5-LE/psl/kbg/2099/psl_EUR-11_CCCma-CanESM2_rcp85_r1-r7i1p1_OURANOS-CRCM5_kbg_daily_209907.nc', 'psl', (<class 'dict'>, [['psl', (<class 'dict'>, [['zlib', 'True'], ['complevel', 5], ['dtype', 'float32']])]])))
kwargs:    {}
Exception: "FileNotFoundError(2, 'No such file or directory')"

2025-09-23 18:23:28,524 - distributed.worker - WARNING - Compute Failed
Key:       compute_and_save_daily_mean-5f6bc7cb-7577-45c5-a94d-7b5aff3fd1c1
Function:  execute_task
args:      ((<function compute_and_save_daily_mean at 0x7f21d8db3c70>, '/work_big/users/clima/portal/CRCM5-LE/psl/kbg/2099/psl_EUR-11_CCCma-CanESM2_rcp85_r1-r7i1p1_OURANOS-CRCM5_kbg_3h_209910.nc', '/work_big/users/clima/portal/CRCM5-LE/psl/kbg/2099/psl_EUR-11_CCCma-CanESM2_rcp85_r1-r7i1p1_OURANOS-CRCM5_kbg_daily_209910.nc', 'psl', (<class 'dict'>, [['psl', (<class 'dict'>, [['zlib', 'True'], ['complevel', 5], ['dtype', 'float32']])]])))
kwargs:    {}
Exception: "FileNotFoundError(2, 'No such file or directory')"

2025-09-23 18:23:28,525 - distributed.worker - WARNING - Compute Failed
Key:       compute_and_save_daily_mean-dd9643a1-5d1d-4a47-bf2e-ba6ca766a132
Function:  execute_task
args:      ((<function compute_and_save_daily_mean at 0x7f21d8db3c70>, '/work_big/users/clima/portal/CRCM5-LE/psl/kbg/2099/psl_EUR-11_CCCma-CanESM2_rcp85_r1-r7i1p1_OURANOS-CRCM5_kbg_3h_209912.nc', '/work_big/users/clima/portal/CRCM5-LE/psl/kbg/2099/psl_EUR-11_CCCma-CanESM2_rcp85_r1-r7i1p1_OURANOS-CRCM5_kbg_daily_209912.nc', 'psl', (<class 'dict'>, [['psl', (<class 'dict'>, [['zlib', 'True'], ['complevel', 5], ['dtype', 'float32']])]])))
kwargs:    {}
Exception: "FileNotFoundError(2, 'No such file or directory')"

2025-09-23 18:23:28,539 - distributed.worker - WARNING - Compute Failed
Key:       compute_and_save_daily_mean-739aa78f-1284-4477-906b-1b1001d693a7
Function:  execute_task
args:      ((<function compute_and_save_daily_mean at 0x7ff8c2f03c70>, '/work_big/users/clima/portal/CRCM5-LE/psl/kbg/2099/psl_EUR-11_CCCma-CanESM2_rcp85_r1-r7i1p1_OURANOS-CRCM5_kbg_3h_209904.nc', '/work_big/users/clima/portal/CRCM5-LE/psl/kbg/2099/psl_EUR-11_CCCma-CanESM2_rcp85_r1-r7i1p1_OURANOS-CRCM5_kbg_daily_209904.nc', 'psl', (<class 'dict'>, [['psl', (<class 'dict'>, [['zlib', 'True'], ['complevel', 5], ['dtype', 'float32']])]])))
kwargs:    {}
Exception: "FileNotFoundError(2, 'No such file or directory')"

2025-09-23 18:23:28,541 - distributed.worker - WARNING - Compute Failed
Key:       compute_and_save_daily_mean-3db88188-b474-42ba-a5b5-704d974bb88e
Function:  execute_task
args:      ((<function compute_and_save_daily_mean at 0x7ff8c2f03c70>, '/work_big/users/clima/portal/CRCM5-LE/psl/kbg/2099/psl_EUR-11_CCCma-CanESM2_rcp85_r1-r7i1p1_OURANOS-CRCM5_kbg_3h_209903.nc', '/work_big/users/clima/portal/CRCM5-LE/psl/kbg/2099/psl_EUR-11_CCCma-CanESM2_rcp85_r1-r7i1p1_OURANOS-CRCM5_kbg_daily_209903.nc', 'psl', (<class 'dict'>, [['psl', (<class 'dict'>, [['zlib', 'True'], ['complevel', 5], ['dtype', 'float32']])]])))
kwargs:    {}
Exception: "FileNotFoundError(2, 'No such file or directory')"

2025-09-23 18:23:28,541 - distributed.worker - WARNING - Compute Failed
Key:       compute_and_save_daily_mean-fd722153-4b78-4489-8fbc-5c36dc3766ae
Function:  execute_task
args:      ((<function compute_and_save_daily_mean at 0x7ff8c2f03c70>, '/work_big/users/clima/portal/CRCM5-LE/psl/kbg/2099/psl_EUR-11_CCCma-CanESM2_rcp85_r1-r7i1p1_OURANOS-CRCM5_kbg_3h_209901.nc', '/work_big/users/clima/portal/CRCM5-LE/psl/kbg/2099/psl_EUR-11_CCCma-CanESM2_rcp85_r1-r7i1p1_OURANOS-CRCM5_kbg_daily_209901.nc', 'psl', (<class 'dict'>, [['psl', (<class 'dict'>, [['zlib', 'True'], ['complevel', 5], ['dtype', 'float32']])]])))
kwargs:    {}
Exception: "FileNotFoundError(2, 'No such file or directory')"

2025-09-23 18:23:28,541 - distributed.worker - WARNING - Compute Failed
Key:       compute_and_save_daily_mean-bb7bc0cd-2a4e-4b58-84d6-1d075c59261d
Function:  execute_task
args:      ((<function compute_and_save_daily_mean at 0x7ff8c2f03c70>, '/work_big/users/clima/portal/CRCM5-LE/psl/kbg/2099/psl_EUR-11_CCCma-CanESM2_rcp85_r1-r7i1p1_OURANOS-CRCM5_kbg_3h_209911.nc', '/work_big/users/clima/portal/CRCM5-LE/psl/kbg/2099/psl_EUR-11_CCCma-CanESM2_rcp85_r1-r7i1p1_OURANOS-CRCM5_kbg_daily_209911.nc', 'psl', (<class 'dict'>, [['psl', (<class 'dict'>, [['zlib', 'True'], ['complevel', 5], ['dtype', 'float32']])]])))
kwargs:    {}
Exception: "FileNotFoundError(2, 'No such file or directory')"

Traceback (most recent call last):
  File "/home/portal/script/python/compute_daily-mean_dask.py", line 56, in <module>
    dask.compute(*dd)
  File "/home/portal/anaconda3/envs/myenv/lib/python3.10/site-packages/dask/base.py", line 661, in compute
    results = schedule(dsk, keys, **kwargs)
  File "/home/portal/script/python/functions_preprocessing.py", line 46, in compute_and_save_daily_mean
    ds = xr.open_dataset(file_in)
  File "/home/portal/anaconda3/envs/myenv/lib/python3.10/site-packages/xarray/backends/api.py", line 539, in open_dataset
    backend_ds = backend.open_dataset(
  File "/home/portal/anaconda3/envs/myenv/lib/python3.10/site-packages/xarray/backends/netCDF4_.py", line 572, in open_dataset
    store = NetCDF4DataStore.open(
  File "/home/portal/anaconda3/envs/myenv/lib/python3.10/site-packages/xarray/backends/netCDF4_.py", line 376, in open
    return cls(manager, group=group, mode=mode, lock=lock, autoclose=autoclose)
  File "/home/portal/anaconda3/envs/myenv/lib/python3.10/site-packages/xarray/backends/netCDF4_.py", line 323, in __init__
    self.format = self.ds.data_model
  File "/home/portal/anaconda3/envs/myenv/lib/python3.10/site-packages/xarray/backends/netCDF4_.py", line 385, in ds
    return self._acquire()
  File "/home/portal/anaconda3/envs/myenv/lib/python3.10/site-packages/xarray/backends/netCDF4_.py", line 379, in _acquire
    with self._manager.acquire_context(needs_lock) as root:
  File "/home/portal/anaconda3/envs/myenv/lib/python3.10/contextlib.py", line 135, in __enter__
    return next(self.gen)
  File "/home/portal/anaconda3/envs/myenv/lib/python3.10/site-packages/xarray/backends/file_manager.py", line 197, in acquire_context
    file, cached = self._acquire_with_cache_info(needs_lock)
  File "/home/portal/anaconda3/envs/myenv/lib/python3.10/site-packages/xarray/backends/file_manager.py", line 215, in _acquire_with_cache_info
    file = self._opener(*self._args, **kwargs)
  File "src/netCDF4/_netCDF4.pyx", line 2463, in netCDF4._netCDF4.Dataset.__init__
  File "src/netCDF4/_netCDF4.pyx", line 2026, in netCDF4._netCDF4._ensure_nc_success
FileNotFoundError: [Errno 2] No such file or directory: b'/work_big/users/clima/portal/CRCM5-LE/psl/kbg/2099/psl_EUR-11_CCCma-CanESM2_rcp85_r1-r7i1p1_OURANOS-CRCM5_kbg_3h_209910.nc'
2025-09-23 18:23:28,567 - distributed.worker.state_machine - WARNING - Async instruction for <Task cancelled name="execute('compute_and_save_daily_mean-8beda5ad-8478-4933-b83e-11c2bb3200a4')" coro=<Worker.execute() done, defined at /home/portal/anaconda3/envs/myenv/lib/python3.10/site-packages/distributed/worker_state_machine.py:3615>> ended with CancelledError
2025-09-23 18:23:28,567 - distributed.worker.state_machine - WARNING - Async instruction for <Task cancelled name="execute('compute_and_save_daily_mean-019edeff-3cf8-46d2-8680-608f1881c1b8')" coro=<Worker.execute() done, defined at /home/portal/anaconda3/envs/myenv/lib/python3.10/site-packages/distributed/worker_state_machine.py:3615>> ended with CancelledError
2025-09-23 18:23:28,568 - distributed.worker.state_machine - WARNING - Async instruction for <Task cancelled name="execute('compute_and_save_daily_mean-d643f1b2-4bc7-440c-b191-6ee917a525a3')" coro=<Worker.execute() done, defined at /home/portal/anaconda3/envs/myenv/lib/python3.10/site-packages/distributed/worker_state_machine.py:3615>> ended with CancelledError
2025-09-23 18:23:28,569 - distributed.worker.state_machine - WARNING - Async instruction for <Task cancelled name="execute('compute_and_save_daily_mean-4993d707-9436-4032-b595-eb0d6fa96eb2')" coro=<Worker.execute() done, defined at /home/portal/anaconda3/envs/myenv/lib/python3.10/site-packages/distributed/worker_state_machine.py:3615>> ended with CancelledError

real	0m2.746s
user	0m6.042s
sys	0m14.702s
